language: r
r: bioc-release
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- ./_build.sh
- ./_deploy.sh
sudo: true
cache:
  packages: true
  directories:
  - $TRAVIS_BUILD_DIR/_bookdown_files
apt_packages: libnetcdf-dev
after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    git clone -b gh-pages \
    https://github.com/yufree/metaworkflow.git \
    book-output
    cd book-output
    cp -r ../_book/* ./
    git add --all *
    git commit -m"Update the book"
    git push origin gh-pages
  fi
deploy:
  api_key: '$GITHUB_API_KEY'