language: r
r: bioc-release

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
  
sudo: true

cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files
    
apt_packages: libnetcdf-dev