language: r
r: bioc-release
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- ./_build.sh
- ./_deploy.sh
sudo: true
cache:
  packages: true
  directories:
  - $TRAVIS_BUILD_DIR/_bookdown_files
apt_packages: libnetcdf-dev
env:
  global:
  - secure: TDaE9L3NE9fvFbD4MDfiHNkiaKBjoYaqEW+mWSGuzanznrHtTobK84d3/wln/ad0aMymIKdBodSEN/IuEqmmxc9KaPDek4aft0nNogE/gmsZEGV72Sy9mLloDv7GIoDGtCBmW9uY1bMqvB9Bv8piANn6J839styDVGmHPXdV6wM0WkZ7p3eKRTRW9j9LHMlbLRd4E2yiFFWbzPIuiMy8gnTuRj8MsjpkOUfWJuWXs4V/5Vfjy/Oh+hnb8SVcptPGYEZMvzKg3YRF/BqmJeYbAijUkpMdwfguqnKCU4gZRAP2nqcvCrCF7MRLtI1lDu5rjargEpl3xBweoIGS0eW4UsPv7Th0wWzd1HyKjE7z+B7Ka+CS6IbhJZJV7V24Z8dplmUcNcxObPh3TgdQ4ss1zztGo82RtXXqxCQbT4DeKAMh8pRCXlKawTufF1lXxuW+Lulv6evw237G74tITwS5mHmvgipcQ3ErUzGs3mQxavnINqfFWHyk51FkGEEjgxyoOKlrACJOinpVqI5lhxHfGhGp9AaLB3BKCFyZgcgHKb7aBOj5Fhs9KwztPGr35na3qBd/n15nQYh19jKcZ9jDAWvWJgHX8ve7BQBVZIvPv4AousVaDBI2lFqM5ryB5f4a7xiMR/3QroL2ENNJo9bLrHDMPuSKTbHbPHVyoedQRc0=
